### PR TITLE
Fix #1518

### LINKED ISSUE #1518: Index was outside the bounds of the array.
I'm still investigating this issue but I wanted to log it and get the ball rolling...

```csharp
            container.RegisterSingleton<IMapper>(() => {
                var profiles = container.GetAllInstances<Profile>();
                var config = new MapperConfiguration(cfg => {
                    cfg.ConstructServicesUsing(container.GetInstance);

                    foreach (var profile in profiles)
                        cfg.AddProfile(profile);
                }); // blows up here..
                return config.CreateMapper();
            });
```

I only have one mapping and this seems to be created okay..

```csharp

        public class ApiMappings : Profile {
            public ApiMappings() {
                CreateMap<UserDescription, EventUserDescription>();
                
                CreateMap<NewOrganization, Organization>();
                CreateMap<Organization, ViewOrganization>().AfterMap((o, vo) => {
                    vo.IsOverHourlyLimit = o.IsOverHourlyLimit();
                    vo.IsOverMonthlyLimit = o.IsOverMonthlyLimit();
                });

                CreateMap<StripeInvoice, InvoiceGridModel>().AfterMap((si, igm) => igm.Id = igm.Id.Substring(3));

                CreateMap<NewProject, Project>();
                CreateMap<Project, ViewProject>();

                CreateMap<NewToken, Token>().ForMember(m => m.Type, m => m.Ignore());
                CreateMap<Token, ViewToken>();
                
                CreateMap<User, ViewUser>();

                CreateMap<NewWebHook, WebHook>();
            }
        }
```

```
System.IndexOutOfRangeException occurred
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=AutoMapper
  StackTrace:
       at AutoMapper.Mappers.CollectionMapperExtensions.MapKeyPairValueExpr(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Type sourceType, Type destType, ParameterExpression itemParam, Expression contextParam)
  InnerException: 
```

``` 
AutoMapper.dll!AutoMapper.Mappers.CollectionMapperExtensions.MapKeyPairValueExpr(AutoMapper.TypeMapRegistry typeMapRegistry = {AutoMapper.TypeMapRegistry}, AutoMapper.IConfigurationProvider configurationProvider = {AutoMapper.MapperConfiguration}, AutoMapper.PropertyMap propertyMap = "Data", System.Type sourceType = {Name = "DataDictionary" FullName = "Exceptionless.Core.Models.DataDictionary"}, System.Type destType = {Name = "DataDictionary" FullName = "Exceptionless.Core.Models.DataDictionary"}, System.Linq.Expressions.ParameterExpression itemParam = {System.Linq.Expressions.TypedParameterExpression}, System.Linq.Expressions.Expression contextParam = {System.Linq.Expressions.TypedParameterExpression})	Unknown
 	AutoMapper.dll!AutoMapper.Mappers.CollectionMapperExtensions.MapCollectionExpression(AutoMapper.TypeMapRegistry typeMapRegistry = {AutoMapper.TypeMapRegistry}, AutoMapper.IConfigurationProvider configurationProvider = {AutoMapper.MapperConfiguration}, AutoMapper.PropertyMap propertyMap = "Data", System.Linq.Expressions.Expression sourceExpression = {System.Linq.Expressions.FullConditionalExpression}, System.Linq.Expressions.Expression destExpression = {System.Linq.Expressions.DefaultExpression}, System.Linq.Expressions.Expression contextExpression = {System.Linq.Expressions.TypedParameterExpression}, System.Func<System.Linq.Expressions.Expression, System.Linq.Expressions.Expression> conditionalExpression = {Method = {System.Reflection.RuntimeMethodInfo}}, System.Type ifInterfaceType = {Name = "Dictionary`2" FullName = "System.Collections.Generic.Dictionary`2"}, AutoMapper.Mappers.CollectionMapperExtensions.MapItem mapItem = {Method = {System.Reflection.RuntimeMethodInfo}})	Unknown
 	AutoMapper.dll!AutoMapper.Mappers.DictionaryMapper.MapExpression(AutoMapper.TypeMapRegistry typeMapRegistry = {AutoMapper.TypeMapRegistry}, AutoMapper.IConfigurationProvider configurationProvider = {AutoMapper.MapperConfiguration}, AutoMapper.PropertyMap propertyMap = "Data", System.Linq.Expressions.Expression sourceExpression = {System.Linq.Expressions.FullConditionalExpression}, System.Linq.Expressions.Expression destExpression = {System.Linq.Expressions.DefaultExpression}, System.Linq.Expressions.Expression contextExpression = {System.Linq.Expressions.TypedParameterExpression})	Unknown
 	AutoMapper.dll!AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(AutoMapper.PropertyMap propertyMap = "Data", AutoMapper.IConfigurationProvider configurationProvider = {AutoMapper.MapperConfiguration}, AutoMapper.TypeMapRegistry typeMapRegistry = {AutoMapper.TypeMapRegistry}, System.Linq.Expressions.ParameterExpression srcParam = {System.Linq.Expressions.TypedParameterExpression}, System.Linq.Expressions.ParameterExpression destParam = {System.Linq.Expressions.TypedParameterExpression}, System.Linq.Expressions.ParameterExpression ctxtParam = {System.Linq.Expressions.TypedParameterExpression})	Unknown
 	AutoMapper.dll!AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(AutoMapper.PropertyMap pm = "Data", AutoMapper.IConfigurationProvider configurationProvider = {AutoMapper.MapperConfiguration}, AutoMapper.TypeMapRegistry registry = {AutoMapper.TypeMapRegistry}, System.Linq.Expressions.ParameterExpression srcParam = {System.Linq.Expressions.TypedParameterExpression}, System.Linq.Expressions.ParameterExpression destParam = {System.Linq.Expressions.TypedParameterExpression}, System.Linq.Expressions.ParameterExpression ctxtParam = {System.Linq.Expressions.TypedParameterExpression})	Unknown
 	AutoMapper.dll!AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(AutoMapper.TypeMap typeMap = "UserDescription" -> "EventUserDescription", AutoMapper.IConfigurationProvider configurationProvider = {AutoMapper.MapperConfiguration}, AutoMapper.TypeMapRegistry registry = {AutoMapper.TypeMapRegistry}, System.Linq.Expressions.ParameterExpression srcParam = {System.Linq.Expressions.TypedParameterExpression}, System.Linq.Expressions.ParameterExpression destParam = {System.Linq.Expressions.TypedParameterExpression}, System.Linq.Expressions.ParameterExpression ctxtParam = {System.Linq.Expressions.TypedParameterExpression}, System.Linq.Expressions.Expression destinationFunc = {System.Linq.Expressions.AssignBinaryExpression}, System.Linq.Expressions.ParameterExpression destination = {System.Linq.Expressions.TypedParameterExpression}, bool constructorMapping = false)	Unknown
 	AutoMapper.dll!AutoMapper.Execution.TypeMapPlanBuilder.BuildMapperFunc(AutoMapper.TypeMap typeMap = "UserDescription" -> "EventUserDescription", AutoMapper.IConfigurationProvider configurationProvider = {AutoMapper.MapperConfiguration}, AutoMapper.TypeMapRegistry typeMapRegistry = {AutoMapper.TypeMapRegistry})	Unknown
 	AutoMapper.dll!AutoMapper.TypeMap.Seal(AutoMapper.TypeMapRegistry typeMapRegistry = {AutoMapper.TypeMapRegistry}, AutoMapper.IConfigurationProvider configurationProvider = {AutoMapper.MapperConfiguration})	Unknown
 	AutoMapper.dll!AutoMapper.MapperConfiguration.Seal(AutoMapper.IConfiguration configuration = {AutoMapper.Configuration.MapperConfigurationExpression})	Unknown
 	AutoMapper.dll!AutoMapper.MapperConfiguration.MapperConfiguration(AutoMapper.Configuration.MapperConfigurationExpression configurationExpression = {AutoMapper.Configuration.MapperConfigurationExpression}, System.Collections.Generic.IEnumerable<AutoMapper.IObjectMapper> mappers = Count = 26)	Unknown
 	AutoMapper.dll!AutoMapper.MapperConfiguration.MapperConfiguration(System.Action<AutoMapper.IMapperConfigurationExpression> configure = {Method = {System.Reflection.RuntimeMethodInfo}}, System.Collections.Generic.IEnumerable<AutoMapper.IObjectMapper> mappers = Count = 26)	Unknown
 	AutoMapper.dll!AutoMapper.MapperConfiguration.MapperConfiguration(System.Action<AutoMapper.IMapperConfigurationExpression> configure = {Method = {System.Reflection.RuntimeMethodInfo}})	Unknown
```

### PR DESCRIPTION
**Pull request by TylerCarlson1**
Have to check for `IDictionary<TKey,TValue>` explicitly for instances that inherit dictionary but aren't generic.  Before would get `IEnumerable<KeyValuePair<TKey,TValue>>`

### CODE REVIEW

File: src/AutoMapper/Mappers/TypeHelper.cs [hunk 1]
```diff
@@ -88,6 +94,20 @@ private static Type GetIEnumerableType(Type enumerableType)
                 return null;
             }
         }
+        private static Type GetIDictionaryType(Type enumerableType)
+        {
+            try
+            {
+                return enumerableType.GetTypeInfo().ImplementedInterfaces.FirstOrDefault(t => t.Name == "IDictionary`2");
+            }
+            catch (AmbiguousMatchException)
```
Comment (lbargaoanu) [inline src/AutoMapper/Mappers/TypeHelper.cs]: That doesn't look good. There is an extension method somewhere ImplementsGenericInterface or smth.

Comment (lbargaoanu) [inline src/AutoMapper/Mappers/TypeHelper.cs]: https://github.com/AutoMapper/AutoMapper/blob/3526ec9371164fe7ef716f47d2e4e73ee4b805e6/src/AutoMapper/Configuration/PrimitiveExtensions.cs#L94
