### PR TITLE
Throwing AutoMapperMappingException when mapping is missed while tryi…

### LINKED ISSUE #2267: NullReferenceException while trying to map expression
### Source/destination types

```csharp
public class Course
{
    public int Id { get; set; }
}

public class CourseModel
{
    public int Id { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg =>
{
    cfg.CreateMap<Course, CourseModel>();
}); 
```

### Expected behavior

Expression should be mapped without any errors.

### Actual behavior

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoMapper.XpressionMapper.XpressionMapperVisitor.FindDestinationFullName(Type typeSource, Type typeDestination, String sourceFullName, List`1 propertyMapInfoList)
   at AutoMapper.XpressionMapper.XpressionMapperVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at AutoMapper.XpressionMapper.XpressionMapperVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at AutoMapper.XpressionMapper.Extensions.MapperExtensions.MapExpression[TDestDelegate](IMapper mapper, LambdaExpression expression)
   at AutoMapper.MapExpression.Issue.Program.Main(String[] args) in ...\AutoMapper.MapExpression.Issue\Program.cs:line 18
```
After investigation I figured out that the reason of NullReference was lack of configuration for mapping CourseModel to Course. After map creation, expression was mapped.
I think AutoMapperMappingException with details of missed mapping types will be more appropriate in this case. In addition, I was surprised why AutoMapper needed reverse mapping.

### Steps to reproduce

```csharp
Expression<Func<Course, bool>> exp = course => course.Id == 1;
var mappedExpresion = Mapper.Instance.MapExpression<Expression<Func<CourseModel, bool>>>(exp);
```
[Program.zip](https://github.com/AutoMapper/AutoMapper/files/1215552/Program.zip)

### PR DESCRIPTION
**Pull request by VadimGatsura**
…ng to map expression.
Fixes #2267.

### CODE REVIEW

File: src/UnitTests/XpressionMapperTests.cs [hunk 1]
```diff
@@ -212,6 +212,27 @@ public void Map_object_when_null_values_are_typed()
...
+                cfg.CreateMap<Car, CarModel>();
+            });
+
+            var customMapper = config.CreateMapper();
+
+            Expression<Func<Car, bool>> expression = car => car.Year == 2017;
+
+            // Act
+            var exception = Assert.Throws<AutoMapperMappingException>(() => customMapper.MapExpression<Expression<Func<CarModel, bool>>>(expression));
+
```
Comment (VadimGatsura) [inline src/UnitTests/XpressionMapperTests.cs]: If I call Map instead of MapExpression I get another exception:

typeof(AutoMapper.AutoMapperMappingException): Error mapping types.

Mapping types:
Expression`1 -> Expression`1
System.Linq.Expressions.Expression`1[[System.Func`2[[AutoMapper.UnitTests.Car, AutoMapper.UnitTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] -> System.Linq.Expressions.Expression`1[[System.Func`2[[AutoMapper.UnitTests.CarModel, AutoMapper.UnitTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

Comment (lbargaoanu) [inline src/UnitTests/XpressionMapperTests.cs]: That's ok.

**Comment by VadimGatsura** [comment]
I changed code related to comments. Please, look again.
