### PR TITLE
Consider ForPath when checking for cycles

### LINKED ISSUE #2813: Mapping with ForPath causes StackOverflowException
https://stackoverflow.com/questions/52503102/why-is-forpath-causing-a-stackoverflowexception-and-formember-is-not?s=19|0.0000

### PR DESCRIPTION
**Pull request by lbargaoanu**
Fixes #2813.

### CODE REVIEW

**Comment by jbogard** [comment]
Is there an issue this fixes? Or just found this separately?

**Comment by lbargaoanu** [comment]
No issue, from SO. The test should crash on master. With SO :)

**Comment by jbogard** [comment]
Ha! Can you create a GH issue with the SO link? Makes the release notes a bit easier.

File: src/AutoMapper/Execution/TypeMapPlanBuilder.cs [hunk 1]
```diff
@@ -93,8 +93,9 @@ private void CheckForCycles(HashSet<TypeMap> typeMapsPath)
             typeMapsPath.Add(_typeMap);
             var defaultPropertyMap = new PropertyMap(default(MemberInfo), null);
             var properties = 
-                _typeMap.GetPropertyMaps().Where(pm=>pm.CanResolveValue()).Select(pm=>new { PropertyTypeMap = ResolvePropertyTypeMap(pm), PropertyMap = pm })
-                .Concat(_typeMap.ConstructorMappingTypes.Select(tp => new { PropertyTypeMap = ResolveTypeMap(tp), PropertyMap = defaultPropertyMap }))
+                _typeMap.GetPropertyMaps().Concat(_typeMap.PathMaps.Select(pm => new PropertyMap(pm))).Where(pm=>pm.CanResolveValue())
```
Comment (jbogard) [inline src/AutoMapper/Execution/TypeMapPlanBuilder.cs]: This is the second place we're wrapping `PathMap` with `PropertyMap`, I wonder if there's maybe a common interface or base class between the two? Then those could be exposed up at `TypeMap`?

Comment (lbargaoanu) [reply src/AutoMapper/Execution/TypeMapPlanBuilder.cs]: Yes, but I don't think that would really help. Because when building the execution plan (the other place) we really want the whole PropertyMap interface (and PathMap implements just a few things). Here probably that interface could be useful, but it's just one place at the moment.

Comment (lbargaoanu) [reply src/AutoMapper/Execution/TypeMapPlanBuilder.cs]: Probably null would work here as well :)

Comment (lbargaoanu) [reply src/AutoMapper/Execution/TypeMapPlanBuilder.cs]: No, I need the type map.

Comment (jbogard) [reply src/AutoMapper/Execution/TypeMapPlanBuilder.cs]: Do you think there's anything to do with the two places in that same class where we're creating PropertyMaps from PathMaps? I guess it seems weird to me we're doing it twice.

Comment (lbargaoanu) [reply src/AutoMapper/Execution/TypeMapPlanBuilder.cs]: Do we want to rewrite CreatePropertyMapFunc so it works both with the common interface and the full property map interface? Or have a more complete interface of which PathMap implements a few methods? I think that's weird too. Doable, but...

Comment (jbogard) [reply src/AutoMapper/Execution/TypeMapPlanBuilder.cs]: Meh. Just leave it for now.
