### PR TITLE
Issue 2246 - UseAsDataSource throwing ArgumentNullException.

### LINKED ISSUE #2246: NullReferenceException with UseAsDataSource
Hi. I've having some trouble using "UseAsDataSource" to query a model queryable with a DTO based where clause. These are the details ([GIST provided](https://gist.github.com/darkcamper/9b6ec4109662a24d3b09069579991090))

### Source/destination types

```csharp
class DTO
{
  public class DTONested
  {
    public bool AnotherBoolean { get; set; }
  }

  public DTONested Nested { get; set; }
}

class Model
{
  public bool ABoolean { get; set; }
}
```

### Mapping configuration

```csharp
cfg.CreateMap<Model, DTO>()
       .ForMember(d => d.Nested, opt => opt.MapFrom(s => s));
cfg.CreateMap<Model, DTO.DTONested>()
       .ForMember(d => d.AnotherBoolean, opt => opt.MapFrom(s => s.ABoolean));
cfg.CreateMap<DTO, Model>()
       .ForMember(d => d.ABoolean, opt => opt.MapFrom(s => s.Nested.AnotherBoolean));
```

### What's happening
If I create an Expression<Func<DTO,bool>> , map it to Expression<Func<Model,bool>> and use it in a Where() call it succeeds as expected

```csharp
Expression<Func<DTO, bool>> expOverDTO = (dto) => dto.Nested.AnotherBoolean;
Expression<Func<Model, bool>> expOverModel = 
     mapper.Map<Expression<Func<DTO, bool>>, Expression<Func<Model, bool>>>(expOverDTO);

var result1 = queryable.Where(expOverModel).ToList();
```
But if I try a similar approach with "UseAsDataSource"  in this way:

```csharp
var result2 = queryable.UseAsDataSource(mapper).For<DTO>().Where(expOverDTO).ToList();
```
A NullReference exception is thrown with the following stack trace:

```
AutoMapper.HashCodeCombiner.Combine[T1,T2](T1 obj1, T2 obj2)
   en System.Collections.Generic.GenericEqualityComparer`1.GetHashCode(T obj)
   en System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   en System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   en AutoMapper.MapperConfiguration.FindTypeMapFor(Type sourceType, Type destinationType)
   en AutoMapper.Mappers.ExpressionMapper.MappingVisitor.GetConvertedSubMemberCall(MemberExpression node)
...
```

I've tried looking in the docs and browsing some old issues but I haven't found any clue about it. Any idea what I'm doing wrong?

Thanks.

### PR DESCRIPTION
**Pull request by dnikolovv**
Fixes #2246.

### CODE REVIEW

**Comment by dnikolovv** [comment]
Okay I've added a test. I'm a bit concerned on the class and test name, but feel free to move them around. Is diff broken now?

**Comment by lbargaoanu** [comment]
You can check that yourself, still broken. The test belongs with the other UseAsDataSource tests.

File: src/AutoMapper/Mappers/ExpressionMapper.cs [hunk 1]
```diff
@@ -226,21 +226,31 @@ protected override Expression VisitConstant(ConstantExpression node)
...
+                var newExpression = subVisitor.Visit(node);
+                _destSubTypes = _destSubTypes.Concat(subVisitor._destSubTypes).ToArray();
+                return newExpression;
+            }
+
+            private Type GetSourceType(PropertyMap propertyMap)
+            {
+                if (propertyMap.SourceMember == null)
+                {
+                    return propertyMap.SourceType;
```
Comment (lbargaoanu) [inline src/AutoMapper/Mappers/ExpressionMapper.cs]: SourceType can still be null here.

File: src/AutoMapper/Mappers/ExpressionMapper.cs [hunk 2]
```diff
@@ -247,7 +247,13 @@ private Type GetSourceType(PropertyMap propertyMap)
             {
                 if (propertyMap.SourceMember == null)
                 {
-                    return propertyMap.SourceType;
+                    return propertyMap.SourceType ??
```
Comment (lbargaoanu) [inline src/AutoMapper/Mappers/ExpressionMapper.cs]: @BlaiseD What to do here?

Comment (dnikolovv) [inline src/AutoMapper/Mappers/ExpressionMapper.cs]: For now I made it throw an exception. Not sure if it's the best thing to do.

Comment (BlaiseD) [inline src/AutoMapper/Mappers/ExpressionMapper.cs]: @lbargaoanu  I believe @TylerCarlson1 knows this code better - or were you just asking my advice generally?

Comment (lbargaoanu) [inline src/AutoMapper/Mappers/ExpressionMapper.cs]: Yeah, you're right. And yes, chip in :)

Comment (lbargaoanu) [inline src/AutoMapper/Mappers/ExpressionMapper.cs]: @TylerCarlson1 Thoughts?

Comment (BlaiseD) [inline src/AutoMapper/Mappers/ExpressionMapper.cs]: If it's similar to XpressionMapper then either the custom expression or the source member should be available - otherwise how can the objects be mapped i.e. `var sourceType = propertyMap.CustomExpression == null
                    ? propertyMap.SourceMember.GetMemberType()
                    : propertyMap.CustomExpression.ReturnType;`

It does not seem like the code needs the source member except to find the type - may want to follow up with @TylerCarlson1

Comment (lbargaoanu) [inline src/AutoMapper/Mappers/ExpressionMapper.cs]: It can be mapped through a resolver.

Comment (BlaiseD) [inline src/AutoMapper/Mappers/ExpressionMapper.cs]: you're right - XpressionMapper throws an exception when propertyMap.ValueResolverConfig != null.  I would do something similar - that's my two cents :)

Comment (TylerCarlson1) [inline src/AutoMapper/Mappers/ExpressionMapper.cs]: I would think `var sourceType = propertyMap.SourceType;` would be sufficient.  If not similar to what @BlaiseD has with for source type but include CustomResolver as it's a LambdaExpression as well.

`PropertyMap.SourceType` has conditions for all types of resolvers types, so that should be used.  If it's null it will return null, but it shouldn't happen unlike what @lbargaoanu says.

The problem is it's a custom expression and `SourceMember.GetMemberType()` doesn't account for custom expressions.  I would think CustomResolver could work as well because it's a lambda but might have to be translated.

Might suggest what @BlaiseD says for setting sourceType for now and can latter test Custom Resolvers and ValueResolverConfig to see if they are supported in UseAsDataSource.

Comment (lbargaoanu) [inline src/AutoMapper/Mappers/ExpressionMapper.cs]: When it's mapped through a resolver it returns typeof(object) (I think I put that one in there :)). Probably it can be null only when it's not mapped.

Comment (TylerCarlson1) [inline src/AutoMapper/Mappers/ExpressionMapper.cs]: Yea I'm not 100% sure what would happen, but it might fail somewhere else.  Not sure if UseAsDataSource would work with a value resolver, but I would guess it wouldn't since it's similar to projection in what it does.  Well even if it did projection wouldn't support it anyways :)
