### PR TITLE
Return the same type on both branches

### LINKED ISSUE #2501: ProjectTo Exception: Argument types do not match
### Source/destination types

```csharp
   //Data Objects
    public class BaseDbObject
    {
        public Guid Id { get; set; }
    }
    public class Calendar : BaseDbObject
    {
        public string Name { get; set; }
        public Guid? ReferenceId { get; set; }
        public virtual Calendar Reference { get; set; }
        public virtual ICollection<CalendarDay> Days { get; set; }
    }
    public class CalendarDay : BaseDbObject
    {
        public DateTime Date { get; set; }
        public Guid DayTypeId { get; set; }
        public Guid CalendarId { get; set; }

        public virtual ValidityDayType DayType { get; set; }
        public virtual global::DataLayer.Calendar Calendar { get; set; }
    }
    public class ValidityDayType : BaseDbObject
    {
        public string Name { get; set; }
        public virtual ICollection<CalendarDay> Days { get; set; }
    }
    //Domain Models
    public class Calendar : ICalendar
    {
        public Guid Id { get; internal set; }
        public string Name { get; internal set; }

        public ICalendar Reference { get; internal set; }
        public virtual ICollection<ICalendarDay> Days { get; set; }
    }
    public class CalendarDay : ICalendarDay
    {
        public Guid Id { get; internal set; }
        public DateTime Date { get; internal set; }
        public IValidityDayType DayType { get; internal set; }
        public ICalendar Calendar { get; internal set; }
    }
    public class ValidityDayType : IValidityDayType
    {
        public Guid Id { get; internal set; }
        public string Name { get; internal set; }
        public ICollection<ICalendarDay> Days { get; internal set; } = ImmutableList<ICalendarDay>.Empty;
    }
```

### Mapping configuration

```csharp
            DisableConstructorMapping();

            CreateMap<DataLayer.Calendar, ICalendar>().As<Implementation.Calendar>();
            CreateMap<DataLayer.Calendar, Implementation.Calendar>();

            CreateMap<DataLayer.CalendarDay, ICalendarDay>().As<Implementation.CalendarDay>();
            CreateMap<DataLayer.CalendarDay, Implementation.CalendarDay>();
            //.ForMember(d => d.DayType, opt => opt.Ignore());

            //This causes the exception! If this part is excluded, the mapping will be proper
            CreateMap<DataLayer.ValidityDayType, IValidityDayType>().As<Implementation.ValidityDayType>();
            CreateMap<DataLayer.ValidityDayType, Implementation.ValidityDayType>();
```

### Version: x.y.z
AutoMapper 6.2.2
AutoMapper.EF6 1.1.1

### Expected behavior
Mapping the models loaded from the database
### Actual behavior
ArgumentException : Argument types do not match.
(At Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse))
### Steps to reproduce
```csharp
            var domainCalendars = set.ProjectTo<ICalendar>(config).ToList();
```
[AutoMapperIssueDemo.zip](https://github.com/AutoMapper/AutoMapper/files/1642464/AutoMapperIssueDemo.zip)

### PR DESCRIPTION
**Pull request by lbargaoanu**
Fixes #2501.

### CODE REVIEW

File: src/IntegrationTests/Inheritance/ProjectToAbstractType.cs [hunk 1]
```diff
@@ -69,4 +72,285 @@ public void Should_project_to_abstract_type()
...
+                DisableConstructorMapping();
+
+                CreateMap<DataLayer.Calendar, ICalendar>().As<Calendar>();
+                CreateMap<DataLayer.Calendar, Calendar>();
+
+                CreateMap<DataLayer.CalendarDay, ICalendarDay>().As<CalendarDay>();
+                CreateMap<DataLayer.CalendarDay, CalendarDay>();
+                //.ForMember(d => d.DayType, opt => opt.Ignore());
+
+                //Include to mapping -> this causes the exception!
```
Comment (bacskaiz) [inline src/IntegrationTests/Inheritance/ProjectToAbstractType.cs]: This comment is unnecessary
