### PR TITLE
Use the existing destination

### LINKED ISSUE #2064: Mapping to readonly IEnumerable property
When trying to map to a readonly IEnumerable property backed by an instance of an IList field AutoMapper throws a NullReferenceException.

### Source/destination types

```csharp
public class Source
{
    private readonly List<string> _myCollection = new List<string>
    {
        "one", "two"
    };

    public string[] MyCollection => _myCollection.ToArray();
}

public class Destination
{
    private IList<string> _myCollection = new List<string>();
    public IEnumerable<string> MyCollection => _myCollection;
}
```

### Mapping configuration

```csharp
CreateMap<Source, Destination>()
                .ForMember(m => m.MyCollection, opt =>
                {
                    opt.MapFrom(src => src.MyCollection);
                    opt.UseDestinationValue();
                });
```

### Expected behavior
The `UseDestinationValue` option should add items to the IList<> backing field. Changing the property to a `IList<string>` works as expected.

### Actual behavior
AutoMapper throws a `NullReferenceException`.

### Steps to reproduce

```csharp
var result = Mapper.Map<Destination>(new Source());
```

### PR DESCRIPTION
**Pull request by lbargaoanu**
Fixes #2064.

### CODE REVIEW

File: src/AutoMapper/Mappers/EnumerableMapper.cs [hunk 1]
```diff
@@ -20,13 +20,13 @@ public Expression MapExpression(IConfigurationProvider configurationProvider, Pr
...
-                destExpression = Default(listType);
+                var listType = typeof(IList<>).MakeGenericType(ElementTypeHelper.GetElementType(destExpression.Type));
+                destExpression = Convert(destExpression, listType);
             }
             return MapCollectionExpression(configurationProvider, profileMap, propertyMap, sourceExpression,
                 destExpression, contextExpression, IfEditableList, typeof(List<>), MapItemExpr);
         }
 
-        private static Expression IfEditableList(Expression dest) => And(TypeIs(dest, typeof(IList)), Not(TypeIs(dest, typeof(Array))));
+        private static Expression IfEditableList(Expression dest) => AndAlso(TypeIs(dest, typeof(IList)), Not(TypeIs(dest, typeof(Array))));
```
Comment (jbogard) [inline src/AutoMapper/Mappers/EnumerableMapper.cs]: Sigh. AndAlso vs And and Or vs OrElse

Comment (lbargaoanu) [inline src/AutoMapper/Mappers/EnumerableMapper.cs]: I don't know what they were thinking.
