### PR TITLE
Only doing null fixing on custom member mappings when there are only …

### LINKED ISSUE #1505: Exception when configuring mappings (worked in 4.2.1)
Since upgrading to 5.0.2 it seems one of my mappings in throwing the following exception - 
`Expression of type 'System.Nullable`1[System.DateTime]' cannot be used for return type 'System.DateTime'`

The destination property is a nullable date time and the mapping is as follows -
`ForMember(Function(dest) dest.EndDate, Sub(opt) opt.MapFrom(Function(src) If(src.ExamType = ExamType.Makeup, src.ExamSchedules.Max(Function(m) m.Schedule.DtEnd), src.ExamSchedules.Where(Function(f) f.Schedule.BHide = False).Max(Function(m) m.Schedule.DtEnd)))).`

If I try to change the destination to just Date then the configuration doesn't throw an exception but I will get an exception later on when my code is run that uses the mapping because there are times where there are no values and it should be null.

Not sure if there is something I'm missing or whether this is a bug or already discussed.

### PR DESCRIPTION
**Pull request by jbogard**
…member accesses, otherwise doing try catches. Fixes #1505

### CODE REVIEW

File: src/UnitTests/NullBehavior.cs [hunk 1]
```diff
@@ -139,6 +152,12 @@ protected override void Because_of()
             }
 
             [Fact]
+            public void Should_return_not_null_for_nullable_properties_that_are_user_defined()
+            {
+                _result.SubExpressionName.ShouldEqual(null);
```
Comment (TylerCarlson1) [inline src/UnitTests/NullBehavior.cs]: ShouldNotEqual null?

Comment (jbogard) [inline src/UnitTests/NullBehavior.cs]: Eh, test name is bad.
