### PR TITLE
Respect PathMappings in unmapped property names list

### LINKED ISSUE #3000: MemberList.Source and ForPath
### Source/destination types

```csharp
class TargetOuter
{
    public TargetInner Inner { get; set; }

    // The properties below should be ignored, they are not relevant
    public int Unrelated { get; set; }
    public string AlsoUnrelated { get; set; }
}

class TargetInner
{
    public string MyProp { get; set; }
}

class Input
{
    public string Source { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(opt => opt.CreateMap<Input, TargetOuter>(MemberList.Source)
                .ForPath(x => x.Inner.MyProp, y => y.MapFrom(x => x.Source)));
```

### Expected behavior
The call of `Mapper.AssertConfigurationIsValid()` should not throw an exception, because all properties from the source (note the `MemberList.Source` configuration value) have been mapped.

### Actual behavior
The call throws the following exception:

```
AutoMapper.AutoMapperConfigurationException: 
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
===============================================================
Input -> TargetOuter (Source member list)
AutoMapper_Assertion.Input -> AutoMapper_Assertion.TargetOuter (Source member list)

Unmapped properties:
Source

   at AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable`1 typeMaps) in C:\projects\automapper\src\AutoMapper\ConfigurationValidator.cs:line 28
   at AutoMapper.MapperConfiguration.AssertConfigurationIsValid() in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 305
   at AutoMapper.Mapper.AssertConfigurationIsValid() in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 179
```

The mapping actually works, which can be seen on the `equal` variable in the reproduce steps below.

### Steps to reproduce

```csharp
var input = new Input() {Source = "Hello World!"};

// The following line throws an exception, see above
// Mapper.AssertConfigurationIsValid();

var output = Mapper.Map<TargetOuter>(input)
var equal = output.Inner.MyProp == input.Source; // equal is true
```

### PR DESCRIPTION
**Pull request by jlnostr**
Instead of only checking expression that have been created using `ForMember`, this also respects the `ForPath` configuration as well
Fixes #3000.

### CODE REVIEW

File: src/AutoMapper/TypeMap.cs [hunk 1]
```diff
@@ -180,11 +180,18 @@ public string[] GetUnmappedPropertyNames()
                     .Where(smc => smc.IsIgnored())
                     .Select(pm => pm.SourceMember.Name).ToList();
 
+                var redirectedPathMembers = PathMaps
```
Comment (lbargaoanu) [inline src/AutoMapper/TypeMap.cs]: Yes, that's the gist of it. But it's kind of ad-hoc. We have this common interface IMemberMap, so I think implementing smth through that interface would be better. So the end result would be smth like `PropertyMaps.Concat(PathMaps).Where`. Doable I think.

Comment (jlnostr) [reply src/AutoMapper/TypeMap.cs]: Yeah, the `TypeMap.MemberMaps` property does this very well. However, I don't think that there's a smart solution (or I didn't understand the codebase enough) using the interface.

Mainly because the information about the source types is saved in totally different places. For `PropertyMap`s, I would use `PropertyMap.SourceMember` while for the `PathMap`, I evaluate an expression. Of course, the `TypeMap` property is common to both types, however I personally don't like the idea of using Reflection again, when it was already done at a previous place (in the `PropertyMap._memberChain` list) for one of the types.

Comment (lbargaoanu) [reply src/AutoMapper/TypeMap.cs]: You can add SourceMember to IMemberMap and implement it in a similar way to PropertyMap.

**Comment by jlnostr** [comment]
I've made some changes to the interface as @lbargaoanu suggested. However, I think that `PropertyMap` can derive from `DefaultMemberMap` to avoid some of the duplicated code.

What do you think about that?

File: src/AutoMapper/PropertyMap.cs [hunk 2]
```diff
@@ -1,165 +1,154 @@
...
-            DestinationMember = destinationMember;
-        }
-
-        public PropertyMap(PropertyMap inheritedMappedProperty, TypeMap typeMap)
-            : this(inheritedMappedProperty.DestinationMember, typeMap) => ApplyInheritedPropertyMap(inheritedMappedProperty);
-
+    using static Expression;
+
+    [DebuggerDisplay("{DestinationMember.Name}")]
+    public class PropertyMap : IMemberMap
```
Comment (lbargaoanu) [inline src/AutoMapper/PropertyMap.cs]: Can you please try fixing the diff somehow? It's probably GitHub's fault, but it does make things difficult.

Comment (jlnostr) [reply src/AutoMapper/PropertyMap.cs]: Seems that there have been a lot of whitespace changes, which here hidden in the IDE. Fix is coming soon, in the meantime, you can disable them on GitHub by setting the diff settings next to the review button.

File: src/AutoMapper/TypeMap.cs [hunk 3]
```diff
@@ -172,13 +172,13 @@ public string[] GetUnmappedPropertyNames()
             }
             else
             {
-                var redirectedSourceMembers = PropertyMaps
-                    .Where(pm => pm.IsMapped && pm.SourceMember != null && pm.SourceMember.Name != pm.DestinationName)
+               var redirectedSourceMembers = MemberMaps
+                    .Where(pm => !pm.Ignored && pm.SourceMember != null && pm.SourceMember.Name != pm.DestinationName)
```
Comment (lbargaoanu) [inline src/AutoMapper/TypeMap.cs]: This seems wrong. Try adding IsMapped in the interface.

**Comment by lbargaoanu** [comment]
Yes, try deriving PropeertMap from DefaultMap.
