### PR TITLE
Fix for #2166 and #2167.

### LINKED ISSUE #2166: Issue with MapExpression when expression checks if a string equals null
When I try to map an expression where there is a check if a string property equals null, I receive the following error:

"InvalidOperationException: The operands for operator 'Equal' do not match the parameters of method 'op_Equality'."

Example:
===================================================================
protected virtual IMapper CreateDefaultMapper<TEntity, TMappedEntity>()
{
      return new MapperConfiguration(cfg =>
      {
                cfg.CreateMap<TEntity, TMappedEntity>().ReverseMap();

                cfg.CreateMissingTypeMaps = true;
      }).CreateMapper();
}
var mapper = CreateDefaultMapper<Order, OrderDto>();
TestMapToDto(mapper, x => x.ShipAddress == null);

void TestMapToDto(IMapper mapper, Expression<Func<OrderDto, bool>> expression)
{
            var mappedExpression = mapper.MapExpression<Expression<Func<Order, bool>>>(expression);
}

===================================================================

I would like to fix it myself, but I'm not really familiar with how to do this, so I'll try and explain what (in my opinion) is the issue.

The error occurs in the class 'XpressionMapperVisitor', in the method "protected override Expression VisitBinary(BinaryExpression node)"

When is change this method so it looks like this;
===================================================================
        protected override Expression VisitBinary(BinaryExpression node)
        {
            if (node.Right is ConstantExpression constantExpression)
            {
                if (constantExpression.Value == null)
                {
                    return base.VisitBinary(node.Left.Type.GetTypeInfo().IsValueType || node.Left.Type == typeof(string)
                        ? node.Update(node.Left, node.Conversion, Expression.Constant(null, node.Left.Type))
                        : node.Update(node.Left, node.Conversion, Expression.Constant(null, typeof(object))));
                }
            }

            constantExpression = node.Left as ConstantExpression;
            if (constantExpression != null)
            {
                if (constantExpression.Value == null)
                {
                    return base.VisitBinary(node.Right.Type.GetTypeInfo().IsValueType || node.Right.Type == typeof(string)
                        ? node.Update(Expression.Constant(null, node.Right.Type), node.Conversion, node.Right)
                        : node.Update(Expression.Constant(null, typeof(object)), node.Conversion, node.Right));
                }
            }

            var newLeft = Visit(node.Left);
            var newRight = Visit(node.Right);
            if ((newLeft.Type.GetTypeInfo().IsGenericType && newLeft.Type.GetGenericTypeDefinition() == typeof(Nullable<>)) ^ (newRight.Type.GetTypeInfo().IsGenericType && newRight.Type.GetGenericTypeDefinition() == typeof(Nullable<>)))
                throw new ArgumentException(string.Format(CultureInfo.CurrentCulture, Resource.cannotCreateBinaryExpressionFormat, newLeft.ToString(), newLeft.Type.Name, newRight.ToString(), newRight.Type.Name));

            return base.VisitBinary(node);
        }
===================================================================

Then the issue is solved.

I added:
-  || node.Left.Type == typeof(string)
and
-  || node.Right.Type == typeof(string)

in the call to the base.VisitBinary(...) method.

### PR DESCRIPTION
**Pull request by BlaiseD**
Replacement PR for #2167.
Fixes #2166.

### CODE REVIEW

File: src/UnitTests/XpressionMapperTests.cs [hunk 1]
```diff
@@ -147,6 +147,39 @@ public void Map__object_including_child_and_grandchild()
 
             //Assert
             Assert.True(users.Count == 2);
+        }
+
+        [Fact]
+        public void Map_object_when_null_values_are_typed()
+        {
+            //Arrange
+            //Expression<Func<UserModel, bool>> selection = s => s != null && s.AccountModel != null && s.AccountModel.Bal > 555.20;
```
Comment (lbargaoanu) [inline src/UnitTests/XpressionMapperTests.cs]: Casting nulls doesn't do the job?

    Expression<Func<UserModel, bool>> selection = s => s != (UserModel) null && s.AccountModel != (AccountModel) null && s.AccountModel.Bal > 555.20;

File: src/AutoMapper/XpressionMapper/XpressionMapperVisitor.cs [hunk 2]
```diff
@@ -34,7 +34,7 @@ protected override Expression VisitParameter(ParameterExpression parameterExpres
         }
 
         protected override Expression VisitMember(MemberExpression node)
-        {
+        {
             if (node.NodeType == ExpressionType.Constant)
```
Comment (lbargaoanu) [inline src/AutoMapper/XpressionMapper/XpressionMapperVisitor.cs]: It can be a member expression and a constant?

File: src/UnitTests/XpressionMapperTests.cs (hunk 1 above)
Comment (BlaiseD) [inline src/UnitTests/XpressionMapperTests.cs]: No - you need the Expression API to set the type.

Comment (lbargaoanu) [inline src/UnitTests/XpressionMapperTests.cs]: Aha, so I guess someone generates these expressions.

File: src/AutoMapper/XpressionMapper/XpressionMapperVisitor.cs (hunk 2 above)
Comment (BlaiseD) [inline src/AutoMapper/XpressionMapper/XpressionMapperVisitor.cs]: Quite likely that code has no value.  The first curly brace below never gets hit stepping through the tests.

```
            if (node.NodeType != ExpressionType.MemberAccess)
            {
            }
```


 don't recall why I wrote it 2 years ago.

**Comment by lbargaoanu** [comment]
I closed that other PR. Will you clean this up or make a new one?

File: src/UnitTests/XpressionMapperTests.cs (hunk 1 above)
Comment (BlaiseD) [inline src/UnitTests/XpressionMapperTests.cs]: Yes - mostly some meta programming component.

**Comment by BlaiseD** [comment]
Done

**Comment by lbargaoanu** [comment]
LGTM.

**Comment by BlaiseD** [comment]
Thanks guys.
@Snijderman  - your tests have been included in the #2177 .
