### PR TITLE
Fixed Issues with property map inheritance

### LINKED ISSUE #842: InvalidCastException when using mapping inheritance
~~~
public class A {};

public class AModel {}
public class BModel : AModel {}

Mapper.CreateMap<A, AModel>()
            .Include<A, BModel>();
Mapper.CreateMap<A, BModel>();
~~~

~~~
Mapper.Map<A, BModel>(anInstanceOfA);
~~~ 

Resulting in:
~~~
System.InvalidCastException: Unable to cast object of type 'AModel' to type 'BModel'. at AutoMapper.MappingEngine.Map[TSource,TDestination](TSource source)
~~~

### PR DESCRIPTION
**Pull request by TylerCarlson1**
Fixes #842, #887, and #893

@jbogard I knew there was a reason GetDerivedTypeFor(Type sourceType) existed.

### CODE REVIEW

**Comment by TylerCarlson1** [comment]
Sorry I didn't notice the differences of #842.  It might still fix the problem, but I don't have a unit test for it.

File: src/AutoMapper/ConfigurationStore.cs [hunk 1]
```diff
@@ -417,10 +417,15 @@ public bool HasOpenGenericTypeMapDefined(ResolutionContext context)
 
         private IEnumerable<TypePair> GetRelatedTypePairs(TypePair root)
         {
-            return
+            var includeOverrideTypePairs =
+                GetAllTypeMaps()
+                    .Where(tm => tm.SourceType.IsAssignableFrom(root.SourceType) && (tm.DestinationTypeOverride ?? tm.DestinationType) != root.DestinationType && tm.DestinationType.IsAssignableFrom(root.DestinationType))
+                    .Select(tm => new TypePair(tm.SourceType,tm.DestinationTypeOverride ?? tm.GetDerivedTypeFor(root.SourceType))).ToList();
```
Comment (jbogard) [inline src/AutoMapper/ConfigurationStore.cs]: Sigh. Yeah I was thinking about this the other day. Good catch.

Comment (TylerCarlson1) [inline src/AutoMapper/ConfigurationStore.cs]: It should hopefully fix #842 as well.  I'll add the example unit test to see if it passes.
I think both are same problem, it's just #842 gets invalid cast exception because it expects inherited type, while other one does not expect it.

Comment (TylerCarlson1) [inline src/AutoMapper/ConfigurationStore.cs]: Actually there's some problems with this in inheritance and #842.  It's quite difficult to determine what is inherited and what is not.

**Comment by TylerCarlson1** [comment]
Fixed issues with #842.  Should be ready to submit now.

And that's why I had HasDerivedTypesToInclude() as well.

Glad you didn't delete them with refactor.  Would of been much harder to remember what I did to fix this problem in 3.3.0

**Comment by martinlong1978** [comment]
Would it be possible to either get this merged, or to have a build in MyGet? Thanks.
